### PR TITLE
Revised recoverers and added recover_supp_rows.princomp()

### PR DESCRIPTION
**Pull request by jbgracey6**
I have updated recover_rows.princomp() to reflect EVD technique. The function now returns a matrix of the same number of columns as the loadings matrix, and of zero rows. This is because, in EVD, we ultimately only have a columns matrix which is transposed to make the rows of the decomposition.

I also added the function recover_supp_rows.princomp so that get_rows() will function as intended. Before this addition, the function get_rows() would return the scores. Now, it will still return the scores, but recognize them as supplemental rows as opposed to the actual rows.

### CODE REVIEW

**Comment by corybrunson** [comment]
Thanks @jbgracey6 for getting this started.

In addition to correcting the `recover_rows()` and `recover_supp_rows()` methods, this will require a synchronized correction to `recover_aug_rows.princomp()`. Perhaps look at [the 'mca' methods](https://github.com/corybrunson/ordr/blob/main/R/methods-mass-mca.r) for an example. The augmentation is used by `fortify.tbl_ord()` and necessary for the plot layers to understand what's what—as encoded in the `.element` column, which takes the value `"active"` for the elements obtained directly from the SVD or EVD and something else, usually `"score"`, for other elements.

It would also be helpful for you to add a 'Details' section to the documentation for the 'princomp' methods. Again, please see the 'mca' methods for a template and refer to [the {roxygen2} documentation](https://roxygen2.r-lib.org/) for understanding of the syntax. You should also add yourself as an author and update one of the `@family` tags to indicate that this is an EVD- rather than an SVD-based technique.

Finally, please ensure that you can run the examples and tests on your end after making these changes—or let me know if something goes wrong. (You can do this line-by-line in the example and test files rather than running `devtools::run_examples()` and `devtools::test()`.) Note that you'll need to update the documentation first, after making the changes to the methods file, e.g. by `devtools::document()`.

**Comment by corybrunson** [comment]
Also! I pushed some changes to the `princomp` branch that i'd made to `main` since you cloned the repo, so you'll need to pull those to your local before pushing new commits to GitHub.

**Comment by jbgracey6** [comment]
Hi again @corybrunson and thanks for the guidance! The latest commit that I've pushed has an updated `@family` section and new `@details` section. Additionally, I have rewritten `recover_aug_rows.princomp()` to return the loadings as active elements, using the `mca` methods as reference for code. However, when running the example script ex-methods-princomp-iris.r, the score element of the augmented matrix is NA. What should be the `name` value there? The centered/scaled data matrix, since that is what gets matrix-multiplied for scores?

**Comment by jbgracey6** [comment]
Hi @corybrunson! My latest commit to `princomp` has a further revised `recover_aug_rows.princomp()` to appropriately handle the supplemental element, scores, based on our last meeting. I have also updated `recover_rows.princomp()` to extract from the scores instead of loadings element, in order to avoid confusion between rows and columns. The example script ex-methods-princomp-iris.r in ordr runs smoothly with these changes, and all of the tests in test-stats-princomp.r pass as long as I run utils.r in my console first (I assume it is okay that I have to run utils.r first?).

**Comment by corybrunson** [comment]
Hi @jbgracey6 and thanks again for the revisions. It seems to work fine on my end—and i had to remind myself that `princomp()`'s output confers inertia onto the scores, despite their being passive elements. In particular, i did not have to source 'utils.r' first, provided i began from an empty session and fake-installed the package using `devtools::load_all()`.

I just pushed one commit that changes some of your code to follow the [Tidyverse style guide](https://style.tidyverse.org/syntax.html#long-lines). Especially since this package is a Tidyverse extension, please refer to this guide when structuring your code. (Don't be perfectionist; just consult the guide when you're not sure.)

I have two final requests:
1. Please fix the `@family` tag to match the existing tag for EVD-based techniques.
2. Please add yourself as an author in 'DESCRIPTION', following the syntax of the existing authors.

**Comment by jbgracey6** [comment]
Hi again @corybrunson. I've gone ahead and made those two changes in my latest commit. Thanks for linking those resources, and let me know if you run into anything else I can fix!

**Comment by corybrunson** [comment]
Hi again @jbgracey6—should be only one more thing: Update the documentation and run a package check. Using {devtools}, these can be done via `document()` and `check()`. Please fix any ERRORs, WARNINGs, or NOTEs you encounter in the check, then commit and push the changes with updated documentation.

(There might be some NOTEs you're not sure how to address. That's fine. But ERRORs and WARNINGs we should resolve before the merge. Report any here that you're unable to resolve.)

**Comment by jbgracey6** [comment]
Hi @corybrunson. I updated the documentation and the check went smoothly except for the following output:

── R CMD check results ────────────────────────────────── ordr 0.1.1.0001 ────
Duration: 1m 36s

❯ checking whether package 'ordr' can be installed ... [21s] WARNING
  See below...

❯ checking package dependencies ... NOTE
  Package suggested but not available for checking: 'mlpack'

0 errors ✔ | 1 warning ✖ | 1 note ✖

I am stumped since the warning says "see below," but the only text below is what I've included here. Do you have any suggestions?

**Comment by jbgracey6** [comment]
@corybrunson Done, thank you!

**Pull request merged**
